var S=Object.defineProperty;var k=t=>{throw TypeError(t)};var A=(t,e,o)=>e in t?S(t,e,{enumerable:!0,configurable:!0,writable:!0,value:o}):t[e]=o;var B=(t,e,o)=>A(t,typeof e!="symbol"?e+"":e,o),P=(t,e,o)=>e.has(t)||k("Cannot "+o);var f=(t,e,o)=>e.has(t)?k("Cannot add the same private member more than once"):e instanceof WeakSet?e.add(t):e.set(t,o);var r=(t,e,o)=>(P(t,e,"access private method"),o);import{S as C,N as E,P as T}from"./assets/vendor-CsU9es7_.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(n){if(n.ep)return;n.ep=!0;const s=o(n);fetch(n.href,s)}})();var c,h;class m{static async fetchCategories(){return r(this,c,h).call(this,"/category-list","Error fetching categories")}static async fetchTopBooks(){return r(this,c,h).call(this,"/top-books","Error fetching top books")}static async fetchBooksByCategory(e){return r(this,c,h).call(this,`/category?category=${encodeURIComponent(e)}`,"Error fetching books by category")}static async fetchBookById(e){return r(this,c,h).call(this,`/${e}`,"Error fetching book by ID")}}c=new WeakSet,h=async function(e,o){try{const i=await fetch(`${this.BASE_URL}${e}`);if(console.log(`[FETCH] ${this.BASE_URL}${e}`),!i.ok)throw new Error(`${o}: ${i.status}`);return await i.json()}catch(i){throw console.error(o,i),i}},f(m,c),B(m,"BASE_URL","https://books-backend.p.goit.global/books");var a,M,y,v;class g{static renderCategories(e,o,i){const s=[{list_name:"All categories"},...e];this._categories=s,this._onCategoryClick=i,this._container=o,r(this,a,y).call(this),window.addEventListener("resize",r(this,a,M).bind(this))}static renderBooks(e,o){if(!(e!=null&&e.length)){o.innerHTML='<li class="no-books-message">No books found</li>';return}o.innerHTML=e.map(i=>r(this,a,v).call(this,i)).join("")}static renderMoreBooks(e,o){o.insertAdjacentHTML("beforeend",e.map(i=>r(this,a,v).call(this,i)).join(""))}static updateCounters(e,o,i,n){i.textContent=e,n.textContent=o}static toggleShowMoreButton(e,o){e.classList.toggle("hidden",!o)}static truncateText(e,o){return(e==null?void 0:e.length)>o?e.substring(0,o)+"…":e}}a=new WeakSet,M=function(){window.innerWidth<1440!==this._isMobile&&r(this,a,y).call(this)},y=function(){this._isMobile=window.innerWidth<1440;const e=this._container,o=this._categories,i=this._onCategoryClick;this._isMobile?(e.innerHTML=`
    <div class="dropdown-wrapper">
      <select id="category-select" class="category-select">
        <option value="" disabled selected hidden>Categories</option>
        ${o.map(s=>`
            <option value="${s.list_name}">
              ${s.list_name}
            </option>`).join("")}
      </select>
    </div>
  `,e.querySelector("#category-select").addEventListener("change",s=>{i(s.target.value)})):(e.innerHTML=o.map(n=>`
          <div 
            class="filter-item ${n.list_name==="All categories"?"active":""}"
            data-category="${n.list_name}"
            role="button"
            tabindex="0"
          >
            ${n.list_name}
          </div>
        `).join(""),e.querySelectorAll(".filter-item").forEach(n=>{n.addEventListener("click",()=>{e.querySelectorAll(".filter-item").forEach(s=>s.classList.remove("active")),n.classList.add("active"),i(n.dataset.category)})}))},v=function(e){return`
      <li class="book-item">
        <div class="book-image">
          ${e.book_image?`<img src="${e.book_image}" 
              alt="${e.title} by ${e.author||"Unknown Author"}" 
              loading="lazy" 
              onerror="this.src='img/no-image.png';">`:'<div class="no-image">No image available</div>'}
        </div>
        <div class="book-details">
          <h3 class="book-title">${this.truncateText(e.title,50)}</h3>
          <p class="book-author">${e.author||"Unknown Author"}</p>
          <p class="book-price">${"$"+e.price}</p>
          <button class="learn-more-btn" data-id="${e._id}">Learn More</button>
        </div>
      </li>
    `},f(g,a);let w="";const I=window.innerWidth>=768?24:10;let l=[],d=0;const p=document.getElementById("books-list"),q=document.getElementById("filters-list"),_=document.getElementById("show-more-btn"),H=document.getElementById("showing-count"),N=document.getElementById("total-count");document.addEventListener("DOMContentLoaded",O);function O(){U(),_.addEventListener("click",F),p.addEventListener("click",onBookClick)}function U(){const t=[{list_name:"Combined Print and E-Book Fiction"},{list_name:"Combined Print and E-Book Nonfiction"},{list_name:"Hardcover Fiction"},{list_name:"Paperback Trade Fiction"},{list_name:"Paperback Nonfiction"},{list_name:"Advice How-To and Miscellaneous"},{list_name:"Childrens Middle Grade Hardcover"}];g.renderCategories(t,q,L),L("All categories")}function L(t){w=t==="All categories"?"":t,j()}async function j(){try{b("loading","Loading books...");let t=w?await m.fetchBooksByCategory(w):(await m.fetchTopBooks()).flatMap(e=>e.books||[]);if(!(t!=null&&t.length))return b("no-books","No books found");l=t,d=Math.min(I,l.length),g.renderBooks(l.slice(0,d),p),$()}catch(t){console.error("❌ Failed to load books:",t),b("error","Could not load books.")}}function F(){const t=Math.min(d+4,l.length),e=l.slice(d,t);e.length&&(g.renderMoreBooks(e,p),d=t,$())}function $(){g.updateCounters(d,l.length,H,N),g.toggleShowMoreButton(_,d<l.length)}function b(t,e){p.innerHTML=`<li class="${t}-message">${e}</li>`}new C(".hero-swiper",{modules:[E],speed:600,loop:!1,keyboard:{enabled:!0,onlyInViewport:!0},slidesPerView:1,spaceBetween:20,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});new C(".events-swiper",{modules:[E,T],speed:350,slidesPerView:"auto",spaceBetween:16,watchOverflow:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,bulletClass:"swiper-pagination-bullet",bulletActiveClass:"swiper-pagination-bullet-active"},breakpoints:{768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}}});function V(){const t=document.body,e=document.querySelector(".mobile-menu"),o=document.querySelector(".mob-menu-btn"),i=document.querySelector(".mob-menu-close-btn");o.addEventListener("click",()=>{e.classList.add("is-open"),t.classList.add("menu-open")}),i.addEventListener("click",()=>{e.classList.remove("is-open"),t.classList.remove("menu-open")}),e.querySelectorAll("a").forEach(n=>{n.addEventListener("click",()=>{e.classList.remove("is-open"),t.classList.remove("menu-open")})}),document.querySelectorAll('a[href^="#"]').forEach(n=>{n.addEventListener("click",s=>{const u=document.querySelector(n.getAttribute("href"));u&&(s.preventDefault(),u.scrollIntoView({behavior:"smooth",block:"start"}),e.classList.remove("is-open"),t.classList.remove("menu-open"))})})}V();
//# sourceMappingURL=index.js.map
